---
- name: Ensure dependencies for git are installed.
  yum: "pkg={{ item }} state=installed"
  with_items:
    - gettext-devel
    - expat-devel
    - curl-devel
    - zlib-devel
    - perl-devel
    - openssl-devel
    - subversion-perl

- name: Download git from kernel.org repo.
  get_url:
    url: "https://www.kernel.org/pub/software/scm/git/git-{{ git_version }}.tar.gz"
    dest: "{{ build_directory }}/git-{{ git_version }}.tar.gz"

- name: Expand git archive to build_directory.
  command: >
    tar -zxf {{ build_directory }}/git-{{ git_version }}.tar.gz
    chdir={{ build_directory }}
    creates={{ build_directory }}/git-{{ git_version }}/README

- name: Verify that git is installed.
  command: which git
  changed_when: false
  failed_when: false
  register: git_installed

- name: Build git in specified prefix location.
  command: >
    make prefix={{ git_install_path }} {{ item }}
    chdir={{ build_directory }}/git-{{ git_version }}
  when: git_installed|failed
  with_items:
    - all
    - install
  sudo: yes